header: ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'income']
feature_ids : [1, 3, 5, 6, 7, 8, 9, 14]
trainingPath: load/adult.data
evaluationPath: load/adult.test
removeIndex: 13